# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/rates" # Location of package manifests
    schedule:
      interval: "weekly"
    commit-message:
      prefix: build
      include: scope
    groups:
      python-dependencies:
        applies-to: version-updates
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ci
      include: scope
    groups:
      github-actions-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
  
  - package-ecosystem: 'gomod'
    directory: "infrastructure/bootstrap/tests/unit" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      github-actions-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
