pull_request_rules:
  - name: "Automatic merge when CI passes"
    conditions:
      - "status-success=dependency-vulnerability-analysis-pr"
      - "status-success=bdd-test-pr"
      - base=main
      - author=dependabot[bot]
    actions:
      merge:
        method: rebase

queue_rules:
  - name: dep-update
    batch_size: 10
    batch_max_wait_time: 30 min
    queue_conditions:
      - author=dependabot[bot]
      - "status-success=dependency-vulnerability-analysis-pr"
      - "status-success=bdd-test-pr"
