pull_request_rules:
  - name: Dependabot
    conditions:
      - "status-success=dependency-vulnerability-analysis-pr"
      - "status-success=bdd-test-pr"
      - base=main
      - author~=^dependabot(|-preview)\[bot\]$
    actions:
      merge:
        method: merge