services:
  app:
    image: 'abhisheksr01/python-postgres-azure:local'
    restart: on-failure
    build:
      context: .
    container_name: app
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      - host=db
      - name=postgres
      - dbname=postgres

  db:
    image: 'postgres:13.5-alpine'
    container_name: db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./db/:/opt/
      - ./scripts/upload.sh:/opt/upload.sh
