version: '3'

services:
  app:
    image: 'abhisheksr01/python-postgres-azure:0.0.1'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      - name=postgres
      - password=secret
      - host=db
      - dbname=postgres

  db:
    image: 'postgres:13.5-alpine'
    container_name: db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./db/:/opt/